name: Delete Package Workflow
on: [pull_request, pull_request_target]

jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Package and Output Response
        run: |
          curl -X DELETE \
            -v \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/users/yellowrook1/packages/npm/testyellowrook1-my-nodejs-package
